name: Test
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build and lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Build and lint
        run: npm run build
